In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.asd_node_interactivity = "all"

In [63]:
import numpy as np

In [82]:
def isint(s):
    try:
        int(s)
        return True
    except(ValueError, TypeError):
        return False

$$ Задание 1.1 $$
Расчет по фомуле:  $z = -\sqrt{x*a^3} + \ln{|\frac{(a - 1,12*x)}{4}|}$, при $a = 23,55$ и $x = 0,9$

In [96]:
a = 23.55
x = 0.9
z = -np.sqrt(x*a**3) + np.log10(np.abs((a - 1.12*x)/4))
print("{:.3f}" .format(z))

-107.669


$$ Задание 1.2 $$
Найти оценки уравнения регрессии, используя метод наименьших квадратов и матричную форму записи уравнений: $$ A = (X^T * X)^{-1} * (X^T * Y) $$

In [97]:
x = np.zeros(shape=(12, 3), dtype=int)
x[:, 0] = 1
N = input("N = ")
if isint(N):
    N = int(N)
    for i in range(12):
        x[i, 1] = np.random.randint(N, N+12)
        x[i, 2] = np.random.randint(60, 82)
    Y = np.random.uniform(13.5, 18.6, 12).reshape(12, 1)
    A = (np.linalg.matrix_power(np.transpose(x).dot(x), -1)).dot(np.transpose(x).dot(Y))
    print("Матрица после вычисления: \n", A)
    Z = A[0] * x[:, 0] + A[1] * x[:, 1] + A[2] * x[:, 2]
    print("Значение Y после формулы: \n", Z.reshape(12, 1))
    print("Исходное значени Y: \n", Y)
else:
    print("Введите целое число")

N =  20


Матрица после вычисления: 
 [[10.073]
 [ 0.086]
 [ 0.054]]
Значение Y после формулы: 
 [[16.501]
 [16.711]
 [15.489]
 [16.236]
 [15.699]
 [16.61 ]
 [16.688]
 [15.652]
 [16.182]
 [16.151]
 [15.653]
 [16.275]]
Исходное значени Y: 
 [[14.435]
 [17.248]
 [14.479]
 [14.39 ]
 [13.597]
 [16.199]
 [18.167]
 [17.171]
 [18.089]
 [17.111]
 [17.378]
 [15.581]]
